#!/bin/sh
#
java -cp "../bin" tw.exact.NewTrieToLatex 1 1 < instance-for-viz.txt > viz1.tex && latexmk -pdf viz1
java -cp "../bin" tw.exact.NewTrieToLatex 1 7 < instance-for-viz.txt > viz2.tex && latexmk -pdf viz2
java -cp "../bin" tw.exact.NewTrieToLatex 2 1 < instance-for-viz.txt > vizc1.tex && latexmk -pdf vizc1
java -cp "../bin" tw.exact.NewTrieToLatex 2 7 < instance-for-viz.txt > vizc2.tex && latexmk -pdf vizc2

